In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/GridlockChallenge/data/raw/train.csv")

In [3]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy

In [5]:
data.isna().sum()

Index               0
geohash             0
day                 0
timestamp           0
demand              0
RoadType          600
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      2495
Weather           797
dtype: int64

In [8]:
data.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [9]:
data.tail()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy

In [10]:
data.describe()

              Index           day        demand  NumberofLanes   Temperature
count  77299.000000  77299.000000  7.729900e+04   77299.000000  74804.000000
mean   38649.000000     48.101838  9.394238e-02       2.014334     16.405354
std    22314.443566      0.302438  1.421905e-01       0.904665      7.359835
min        0.000000     48.000000  6.245650e-07       1.000000    -14.935097
25%    19324.500000     48.000000  1.822723e-02       1.000000     11.430473
50%    38649.000000     48.000000  4.775994e-02       2.000000     16.382587
75%    57973.500000     48.000000  1.085951e-01       3.000000     21.298833
max    77298.000000     49.000000  1.000000e+00       5.000000     48.251433

In [11]:
data['RoadType'].unique()

array([nan, 'Residential', 'Street', 'Highway'], dtype=object)

In [12]:
data.columns

Index(['Index', 'geohash', 'day', 'timestamp', 'demand', 'RoadType',
       'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature',
       'Weather'],
      dtype='object')

In [13]:
data['timestamp'].unique()

array(['0:0', '0:15', '0:30', '0:45', '1:0', '1:15', '1:30', '1:45',
       '2:0', '2:15', '2:30', '2:45', '3:0', '3:15', '3:30', '3:45',
       '4:0', '4:15', '4:30', '4:45', '5:0', '5:15', '5:30', '5:45',
       '6:0', '6:15', '6:30', '6:45', '7:0', '7:15', '7:30', '7:45',
       '8:0', '8:15', '8:30', '8:45', '9:0', '9:15', '9:30', '9:45',
       '10:0', '10:15', '10:30', '10:45', '11:0', '11:15', '11:30',
       '11:45', '12:0', '12:15', '12:30', '12:45', '13:0', '13:15',
       '13:30', '13:45', '14:0', '14:15', '14:30', '14:45', '15:0',
       '15:15', '15:30', '15:45', '16:0', '16:15', '16:30', '16:45',
       '17:0', '17:15', '17:30', '17:45', '18:0', '18:15', '18:30',
       '18:45', '19:0', '19:15', '19:30', '19:45', '20:0', '20:15',
       '20:30', '20:45', '21:0', '21:15', '21:30', '21:45', '22:0',
       '22:15', '22:30', '22:45', '23:0', '23:15', '23:30', '23:45'],
      dtype=object)

In [14]:
data['Temperature'] = data.groupby('timestamp')['Temperature'].transform(lambda x: x.fillna(x.median()))

In [15]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,16.683214,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.683214,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy

In [16]:
data.isnull().sum()

Index              0
geohash            0
day                0
timestamp          0
demand             0
RoadType         600
NumberofLanes      0
LargeVehicles      0
Landmarks          0
Temperature        0
Weather          797
dtype: int64

In [30]:
df = data.groupby('Temperature')['Weather'].value_counts().reset_index()

In [31]:
df

       Temperature Weather  count
0       -14.935097   Snowy      1
1       -14.285316   Snowy      1
2       -13.360564   Snowy      1
3       -12.224457   Snowy      1
4       -12.121729   Snowy      1
...            ...     ...    ...
74353    45.372055   Sunny      1
74354    46.225849   Sunny      1
74355    46.546123   Sunny      1
74356    46.636317   Sunny      1
74357    48.251433   Sunny      1

[74358 rows x 3 columns]

In [32]:
df.describe()

        Temperature         count
count  74358.000000  74358.000000
mean      16.401614      1.028833
std        7.340412      0.508441
min      -14.935097      1.000000
25%       11.453678      1.000000
50%       16.382762      1.000000
75%       21.269725      1.000000
max       48.251433     23.000000

In [39]:
# Best: Fill missing RoadType using the mode of that specific geographic area (geohash)
data['RoadType'] = data.groupby('geohash')['RoadType'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown'))

In [41]:
data.isnull().sum()

Index              0
geohash            0
day                0
timestamp          0
demand             0
RoadType           0
NumberofLanes      0
LargeVehicles      0
Landmarks          0
Temperature        0
Weather          797
dtype: int64

In [43]:
data['temp_bins'] = pd.cut(data['Temperature'], bins=range(int(data['Temperature'].min())-5, int(data['Temperature'].max())+5, 5))

In [44]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,temp_bins
0,0,qp02z1,48,0:0,0.048804,Residential,1,Not Allowed,No,16.683214,NaN,"(16, 21]"
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny,"(31, 36]"
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny,"(21, 26]"
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.683214,Rainy,"(16, 21]"
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy,"(6, 11]"
...,...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy,"(11, 16]"
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy,"(11, 16]"
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny,"(16, 21]"
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny,"(21, 26]"
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy,"(1, 6]"

In [45]:
data['Weather'] = data.groupby('temp_bins', dropna=False)['Weather'].transform(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Clear')
)

# Drop the temporary bin column when done
data = data.drop(columns=['temp_bins'])

/var/folders/9x/3x7xy3b937b7s21dnh9vzpp00000gn/T/ipykernel_19900/271494591.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data['Weather'] = data.groupby('temp_bins', dropna=False)['Weather'].transform(

In [46]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,Residential,1,Not Allowed,No,16.683214,Foggy
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.683214,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy

In [47]:
data.isnull().sum()

Index            0
geohash          0
day              0
timestamp        0
demand           0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
dtype: int64

In [49]:
data['LargeVehicles'].unique()

array(['Not Allowed', 'Allowed'], dtype=object)