In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/GridlockChallenge/data/half_processed/cleaned_data.csv")

In [3]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,Residential,1,Not Allowed,No,16.683214,Foggy
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.683214,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy

In [4]:
data.isnull().sum()

Index            0
geohash          0
day              0
timestamp        0
demand           0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
dtype: int64

In [8]:
data['timestamp'].unique()

array(['0:0', '0:15', '0:30', '0:45', '1:0', '1:15', '1:30', '1:45',
       '2:0', '2:15', '2:30', '2:45', '3:0', '3:15', '3:30', '3:45',
       '4:0', '4:15', '4:30', '4:45', '5:0', '5:15', '5:30', '5:45',
       '6:0', '6:15', '6:30', '6:45', '7:0', '7:15', '7:30', '7:45',
       '8:0', '8:15', '8:30', '8:45', '9:0', '9:15', '9:30', '9:45',
       '10:0', '10:15', '10:30', '10:45', '11:0', '11:15', '11:30',
       '11:45', '12:0', '12:15', '12:30', '12:45', '13:0', '13:15',
       '13:30', '13:45', '14:0', '14:15', '14:30', '14:45', '15:0',
       '15:15', '15:30', '15:45', '16:0', '16:15', '16:30', '16:45',
       '17:0', '17:15', '17:30', '17:45', '18:0', '18:15', '18:30',
       '18:45', '19:0', '19:15', '19:30', '19:45', '20:0', '20:15',
       '20:30', '20:45', '21:0', '21:15', '21:30', '21:45', '22:0',
       '22:15', '22:30', '22:45', '23:0', '23:15', '23:30', '23:45'],
      dtype=object)

In [9]:
time_parts = data['timestamp'].str.split(':', expand=True)

In [11]:
data['hour'] = time_parts[0].astype(int)
data['minute'] = time_parts[1].astype(int)

In [12]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,hour,minute
0,0,qp02z1,48,0:0,0.048804,Residential,1,Not Allowed,No,16.683214,Foggy,0,0
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny,0,0
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny,0,0
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.683214,Rainy,0,0
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy,2,0
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy,2,0
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny,2,0
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny,2,0
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy,2,0

In [13]:
data['minute_of_day'] = data['hour'] * 60 + data['minute']

In [14]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,hour,minute,minute_of_day
0,0,qp02z1,48,0:0,0.048804,Residential,1,Not Allowed,No,16.683214,Foggy,0,0,0
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny,0,0,0
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny,0,0,0
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.683214,Rainy,0,0,0
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy,2,0,120
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy,2,0,120
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny,2,0,120
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny,2,0,120
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy,2,0,120

In [16]:
MINUTES_IN_DAY = 1440.0
data['time_sin'] = np.sin(2 * np.pi * data['minute_of_day'] / MINUTES_IN_DAY)
data['time_cos'] = np.cos(2 * np.pi * data['minute_of_day'] / MINUTES_IN_DAY)

In [17]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,hour,minute,minute_of_day,time_sin,time_cos
0,0,qp02z1,48,0:0,0.048804,Residential,1,Not Allowed,No,16.683214,Foggy,0,0,0,0.0,1.000000
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny,0,0,0,0.0,1.000000
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny,0,0,0,0.0,1.000000
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.683214,Rainy,0,0,0,0.0,1.000000
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy,0,0,0,0.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy,2,0,120,0.5,0.866025
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy,2,0,120,0.5,0.866025
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny,2,0,120,0.5,0.866025
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny,2,0,120,0.5,0.866025
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy,2,0,120,0.5,0.866025

In [20]:
import pygeohash as pgh

# Decode geohash into center latitude and longitude
data['latitude'] = data['geohash'].apply(lambda x: pgh.decode(x)[0])
data['longitude'] = data['geohash'].apply(lambda x: pgh.decode(x)[1])

In [21]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,hour,minute,minute_of_day,time_sin,time_cos,latitude,longitude
0,0,qp02z1,48,0:0,0.048804,Residential,1,Not Allowed,No,16.683214,Foggy,0,0,0,0.0,1.000000,-5.484924,90.664673
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny,0,0,0,0.0,1.000000,-5.462952,90.686646
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny,0,0,0,0.0,1.000000,-5.462952,90.708618
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.683214,Rainy,0,0,0,0.0,1.000000,-5.462952,90.862427
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy,0,0,0,0.0,1.000000,-5.457458,90.675659
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy,2,0,120,0.5,0.866025,-5.237732,90.796509
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy,2,0,120,0.5,0.866025,-5.237732,90.807495
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny,2,0,120,0.5,0.866025,-5.237732,90.818481
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny,2,0,120,0.5,0.866025,-5.237732,90.906372
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy,2,0,120,0.5,0.866025,-5.237732,90.939331

In [22]:
data = data.sort_values(by=['geohash', 'timestamp']).reset_index(drop=True)

# Create a lag feature for the previous timestamp's demand
data['demand_lag_1'] = data.groupby('geohash')['demand'].shift(1)
data['demand_lag_2'] = data.groupby('geohash')['demand'].shift(2)

# Fill the first few empty rows created by shifting with the median demand
data['demand_lag_1'] = data['demand_lag_1'].fillna(data['demand'].median())
data['demand_lag_2'] = data['demand_lag_2'].fillna(data['demand'].median())

In [23]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,hour,minute,minute_of_day,time_sin,time_cos,latitude,longitude,demand_lag_1,demand_lag_2
0,36776,qp02yc,48,10:30,0.046790,Residential,1,Not Allowed,No,22.809028,Sunny,10,30,630,0.382683,-0.923880,-5.484924,90.653687,0.047760,0.047760
1,37683,qp02yc,48,10:45,0.021158,Residential,1,Not Allowed,No,16.543659,Foggy,10,45,645,0.321439,-0.946930,-5.484924,90.653687,0.046790,0.047760
2,2911,qp02yc,48,1:0,0.005397,Residential,3,Allowed,Yes,11.299877,Rainy,1,0,60,0.258819,0.965926,-5.484924,90.653687,0.021158,0.046790
3,8010,qp02yc,48,2:30,0.012944,Residential,2,Not Allowed,Yes,32.142120,Sunny,2,30,150,0.608761,0.793353,-5.484924,90.653687,0.005397,0.021158
4,8905,qp02yc,48,2:45,0.025961,Residential,1,Not Allowed,No,15.811063,Foggy,2,45,165,0.659346,0.751840,-5.484924,90.653687,0.012944,0.005397
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,32309,qp0dnj,48,9:0,0.023207,Residential,2,Not Allowed,Yes,8.420461,Rainy,9,0,540,0.707107,-0.707107,-5.243225,90.972290,0.033207,0.021213
77295,33179,qp0dnj,48,9:15,0.028085,Residential,1,Not Allowed,No,28.507294,Sunny,9,15,555,0.659346,-0.751840,-5.243225,90.972290,0.023207,0.033207
77296,34062,qp0dnj,48,9:30,0.049272,Residential,1,Not Allowed,No,2.985736,Snowy,9,30,570,0.608761,-0.793353,-5.243225,90.972290,0.028085,0.023207
77297,60798,qp0dnn,48,19:45,0.007751,Residential,2,Not Allowed,Yes,13.101840,Rainy,19,45,1185,-0.896873,0.442289,-5.237732,90.972290,0.047760,0.047760
77298,16144,qp0dnn,48,4:30,0.000738,Residential,3,Allowed,Yes,11.099957,Rainy,4,30,270,0.923880,0.382683,-5.237732,90.972290,0.007751,0.047760

In [24]:
data.isnull().sum()

Index            0
geohash          0
day              0
timestamp        0
demand           0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
hour             0
minute           0
minute_of_day    0
time_sin         0
time_cos         0
latitude         0
longitude        0
demand_lag_1     0
demand_lag_2     0
dtype: int64

In [25]:
from sklearn.cluster import KMeans

# Group coordinates into clusters (e.g., 20 distinct traffic zones)
coords = data[['latitude', 'longitude']]
kmeans = KMeans(n_clusters=20, random_state=42, n_init=10)

data['traffic_cluster_id'] = kmeans.fit_predict(coords)

In [26]:
data

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,...,hour,minute,minute_of_day,time_sin,time_cos,latitude,longitude,demand_lag_1,demand_lag_2,traffic_cluster_id
0,36776,qp02yc,48,10:30,0.046790,Residential,1,Not Allowed,No,22.809028,...,10,30,630,0.382683,-0.923880,-5.484924,90.653687,0.047760,0.047760,15
1,37683,qp02yc,48,10:45,0.021158,Residential,1,Not Allowed,No,16.543659,...,10,45,645,0.321439,-0.946930,-5.484924,90.653687,0.046790,0.047760,15
2,2911,qp02yc,48,1:0,0.005397,Residential,3,Allowed,Yes,11.299877,...,1,0,60,0.258819,0.965926,-5.484924,90.653687,0.021158,0.046790,15
3,8010,qp02yc,48,2:30,0.012944,Residential,2,Not Allowed,Yes,32.142120,...,2,30,150,0.608761,0.793353,-5.484924,90.653687,0.005397,0.021158,15
4,8905,qp02yc,48,2:45,0.025961,Residential,1,Not Allowed,No,15.811063,...,2,45,165,0.659346,0.751840,-5.484924,90.653687,0.012944,0.005397,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,32309,qp0dnj,48,9:0,0.023207,Residential,2,Not Allowed,Yes,8.420461,...,9,0,540,0.707107,-0.707107,-5.243225,90.972290,0.033207,0.021213,9
77295,33179,qp0dnj,48,9:15,0.028085,Residential,1,Not Allowed,No,28.507294,...,9,15,555,0.659346,-0.751840,-5.243225,90.972290,0.023207,0.033207,9
77296,34062,qp0dnj,48,9:30,0.049272,Residential,1,Not Allowed,No,2.985736,...,9,30,570,0.608761,-0.793353,-5.243225,90.972290,0.028085,0.023207,9
77297,60798,qp0dnn,48,19:45,0.007751,Residential,2,Not Allowed,Yes,13.101840,...,19,45,1185,-0.896873,0.442289,-5.237732,90.972290,0.047760,0.047760,9
77298,16144,qp0dnn,48,4:30,0.000738,Residential,3,Allowed,Yes,11.099957,...,4,30,270,0.923880,0.382683,-5.237732,90.972290,0.007751,0.047760,9

In [27]:
data.columns

Index(['Index', 'geohash', 'day', 'timestamp', 'demand', 'RoadType',
       'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature', 'Weather',
       'hour', 'minute', 'minute_of_day', 'time_sin', 'time_cos', 'latitude',
       'longitude', 'demand_lag_1', 'demand_lag_2', 'traffic_cluster_id'],
      dtype='object')

In [28]:
data['traffic_cluster_id'] = data['traffic_cluster_id'].astype('category')

In [29]:
data = pd.get_dummies(data, columns=['Weather', 'RoadType','LargeVehicles','Landmarks'], drop_first=True, dtype=int)

In [30]:
data

,Index,geohash,day,timestamp,demand,NumberofLanes,Temperature,hour,minute,minute_of_day,...,demand_lag_1,demand_lag_2,traffic_cluster_id,Weather_Rainy,Weather_Snowy,Weather_Sunny,RoadType_Residential,RoadType_Street,LargeVehicles_Not Allowed,Landmarks_Yes
0,36776,qp02yc,48,10:30,0.046790,1,22.809028,10,30,630,...,0.047760,0.047760,15,0,0,1,1,0,1,0
1,37683,qp02yc,48,10:45,0.021158,1,16.543659,10,45,645,...,0.046790,0.047760,15,0,0,0,1,0,1,0
2,2911,qp02yc,48,1:0,0.005397,3,11.299877,1,0,60,...,0.021158,0.046790,15,1,0,0,1,0,0,1
3,8010,qp02yc,48,2:30,0.012944,2,32.142120,2,30,150,...,0.005397,0.021158,15,0,0,1,1,0,1,1
4,8905,qp02yc,48,2:45,0.025961,1,15.811063,2,45,165,...,0.012944,0.005397,15,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,32309,qp0dnj,48,9:0,0.023207,2,8.420461,9,0,540,...,0.033207,0.021213,9,1,0,0,1,0,1,1
77295,33179,qp0dnj,48,9:15,0.028085,1,28.507294,9,15,555,...,0.023207,0.033207,9,0,0,1,1,0,1,0
77296,34062,qp0dnj,48,9:30,0.049272,1,2.985736,9,30,570,...,0.028085,0.023207,9,0,1,0,1,0,1,0
77297,60798,qp0dnn,48,19:45,0.007751,2,13.101840,19,45,1185,...,0.047760,0.047760,9,1,0,0,1,0,1,1
77298,16144,qp0dnn,48,4:30,0.000738,3,11.099957,4,30,270,...,0.007751,0.047760,9,1,0,0,1,0,0,1

In [31]:
data.isnull().sum()

Index                        0
geohash                      0
day                          0
timestamp                    0
demand                       0
NumberofLanes                0
Temperature                  0
hour                         0
minute                       0
minute_of_day                0
time_sin                     0
time_cos                     0
latitude                     0
longitude                    0
demand_lag_1                 0
demand_lag_2                 0
traffic_cluster_id           0
Weather_Rainy                0
Weather_Snowy                0
Weather_Sunny                0
RoadType_Residential         0
RoadType_Street              0
LargeVehicles_Not Allowed    0
Landmarks_Yes                0
dtype: int64

In [32]:
data.columns

Index(['Index', 'geohash', 'day', 'timestamp', 'demand', 'NumberofLanes',
       'Temperature', 'hour', 'minute', 'minute_of_day', 'time_sin',
       'time_cos', 'latitude', 'longitude', 'demand_lag_1', 'demand_lag_2',
       'traffic_cluster_id', 'Weather_Rainy', 'Weather_Snowy', 'Weather_Sunny',
       'RoadType_Residential', 'RoadType_Street', 'LargeVehicles_Not Allowed',
       'Landmarks_Yes'],
      dtype='object')

In [33]:
data.to_csv("/Users/nidhishgupta/Desktop/GridlockChallenge/data/processed/training_data.csv",index = False)